// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gerpzlgzhexzujqcrazj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcnB6bGd6aGV4enVqcWNyYXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMjU0NDAsImV4cCI6MjA1NDkwMTQ0MH0.UPQoBBqzUcrytTfrMhsjQ3kzWMPy2CMx5ZbEIKhC9k8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);